version: '3.9'


services:
 mongoDBTest:
  container_name: mongo 
  image: mongo:5.0
  ports:
    - 27017:27017
#   enviroment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root123
  
  volumes: 
     - ./mongo_data:/data/db
